### ISSUE TITLE
General discussion about GitHub Workflows

### ISSUE THREAD

**Issue by jtxa** [sierrafoxtrot/srecord#8]
This is a list of potential things to do in the workflow.
Attention: this message may be updated based on discussions and implemented PRs.

# CI (Continuous Integration)

## systems

- [x] new linux (see #7)
- [ ] old linux (maybe via docker, e.g. centos)
- [ ] windows: msbuild with VC++
- [ ] windows: ninja with VC++/MinGW
- [ ] windows: msys
- [ ] windows: cygwin
- [ ] macos
- [ ] select which compiler shall be used on which machine/os

## jobs/steps

- [x] simple build one linux with gcc & clang, run tests (see #7)
- [x] build docs (see #7)
- [ ] build package for system
- [ ] install package
- [ ] test installed executables
- [x] docs (see #7)

# CD (Continuous Delivery)

- [ ] build all release packages
- [ ] build PDF
- [ ] build doxygen
- [ ] build web-site
- [ ] publish web-site
- [ ] publish release packages
- [ ] publish to Ubuntu ppa and alike

# QA (Quality assurance)

## Different build with special settings

- [ ] with fixed language version
- [ ] with coverage

## Possible checks with [MegaLinter](https://oxsecurity.github.io/megalinter/latest/)

- [ ] `*.sh`: shellcheck, shfmt
- [ ] `*.css`: stylelint
- [ ] `*.html`: djlint and/or htmllint
- [ ] `*.md`: markdownlint, markdown-link-check and/or markdown-table-formatter
- [ ] `*.ym`l: yamllint and/or v8r
- [ ] prettier (formatting of sh, yml, md)
- [ ] editorconfig-checker
- [ ] cspell

## Static code analyzers

- [ ] clang-tidy
- [ ] clang-format
- [ ] IWYU
- [ ] LWYU
- [ ] cpplint
- [ ] Cppcheck
- [ ] CodeQL
- [ ] scan-build

maybe done with the help of [CodeChecker](https://github.com/Ericsson/codechecker/)

more may be found [here](https://github.com/analysis-tools-dev/static-analysis) or [here](https://github.com/codefactor-io/awesome-static-analysis)

## Statistics
- [ ] [scc](https://github.com/boyter/scc/actions)
- [ ] Code Coverage, e.g. with gcovr

# Dependabot

- [ ] [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
  may be useful for being up-to-date on the github actions used in workflows.

**Comment by jtxa** [comment]
I know it's a long list, but I just wanted to write down the ideas of what may be interesting.
Maybe some people are interested in some of the points.

**Comment by sierrafoxtrot** [comment]
It's a great list, if half of it gets done it will be a massive win. I'm super keen to get a truly native build going which would be covered by the msbuild/VC++ I guess. Something we can ship without the DLLs. Sadly without msys2 or similar, running the shell script tests gets a little tricky. 

I'm going to take a look at look at "build package for system" as I figure a simple cpack should be a nice first task. As I mentioned, I haven't dabbled too much with the workflows part if github before.

**Comment by jtxa** [comment]
Probably next week I can try to start with a Windows workflow, the GitHub runner has MSYS2 and CYGWIN preinstalled.
So we can at least make sure, that they won't break.
With my own old CMake script I have crosscompiled from Debian to Windows. So we will definitely also get something native running, it just needs some time. As I also do not have any experience with GitHub workflows, I need to google and read a lot.
